### ISSUE TITLE
Error on fresh Next.js project

### ISSUE THREAD

**Issue by jaredpalmer** [jxnblk/create-docs#1]
```
{ TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/clean-tag/dist.js:32
:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/system-components/di
st/System.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17) sourceMapsApplied: true }
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/clean-tag/dist.js:32:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/system-components/dist/System.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/clean-tag/dist.js:32:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/system-components/dist/System.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/clean-tag/dist.js:32:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/system-components/dist/System.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/clean-tag/dist.js:32:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jared/workspace/github/jaredpalmer/formik/docs2/node_modules/system-components/dist/System.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)```

**Comment by jxnblk** [comment]
<img width="254" alt="screenshot 2018-07-14 19 03 17" src="https://user-images.githubusercontent.com/3451712/42729019-a0a88126-8798-11e8-93cf-08824b6aecb8.png">

**Comment by jaredpalmer** [comment]
😎 . x0 works 💯 and looks great too! nice job with this.

**Comment by jxnblk** [comment]
Thanks! Yeah I’ll get next.js going soon but def needs a lot more work

**Comment by jxnblk** [comment]
Still rough around the edges, but I think the next.js version *should* work with a fresh install. The error looks like it was related to a bug with the dependencies in [clean-tag](https://github.com/jxnblk/styled-system/commit/910eb31d5068b9eb50a14e9342ea1f0df31b502b)
